# The Microsoft Store screenshots, as recipes rather than as prose.
#
# `take-shots.ps1` beside this takes a set given the recipes for it, and
# `screenshot.ps1` under that is the driver and knows nothing about Slipcase.
# Both are generated by ship and the same in every repository with a window to
# photograph. This file is the part that is Slipcase's - which container, which
# frame, and what the desktop has to look like before the shutter.
#
# Everything a person would change to retake the set lives at the top, and
# running it by hand on the Windows machine is the same command CI would:
#
#     packaging\demo-container.sh          # in Git bash: builds the container
#     powershell -ExecutionPolicy Bypass -File packaging\windows\shots.ps1
#
# WHAT THE SET SHOWS, AND WHY IT IS FOUR
#
# Two containers and two themes. The containers are the same one twice, the
# second carrying a `Zone.Identifier`, so the card's provenance line reads
# *This container arrived from elsewhere, and the payload will carry that* -
# which is the one thing in this application worth a slot that a still frame
# can show.
#
# Light leads, and that is a decision rather than a preference. The application
# follows the system theme, and a fresh Windows 10 or 11 installation runs apps
# light, so most people reading this listing are reading it on a light desktop.
# The dark pair is kept because following the theme is worth showing and costs
# two slots out of ten. `packaging/submission-notes.md` carries the same reasoning
# for the reader who never opens this file.
#
# The theme is the desktop's and no click reaches it, so it is set before each
# launch and read back. A shot taken after a theme that did not take is a
# duplicate of its pair, which is the sort of thing that reaches a listing.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

[CmdletBinding()]
param(
    # One plain capture, and nothing else. This is how a coordinate gets
    # measured when a recipe below grows one.
    [switch] $Reference,
    [string] $OutDir,
    # The packaged application, as `<PackageFamilyName>!<ApplicationId>`. With
    # it the frames are of the package a person installs; without it the shell
    # decides, which is right only where nothing else claims `.slpc`.
    [string] $Aumid
)

$ErrorActionPreference = 'Stop'

. "$PSScriptRoot\take-shots.ps1"

$root = (Resolve-Path (Join-Path $PSScriptRoot '..\..')).Path

# --- the configuration ------------------------------------------------------

# 1366x768 is the Microsoft Store's minimum for a desktop screenshot, and is
# deliberately not exceeded: the window at that size looks like a window, and
# at 1920x1080 it looks like a window with a great deal of nothing beside it.
$WIDTH = 1366
$HEIGHT = 768

# What `packaging/demo-container.sh` builds. Its archive timestamps are pinned,
# so any machine rebuilds the same bytes and the pictures match the container
# the review notes send a tester to.
$CONTAINER = Join-Path $root 'dist\quarterly-report.pdf.slpc'

# The same container under a second name, marked as downloaded. A copy rather
# than a mark on the original, so a rerun does not find the first shot's
# container already carrying the stream the second shot is about.
$ARRIVED = Join-Path $root 'dist\arrived-quarterly-report.pdf.slpc'

# The window's process, and the sibling that would hold the container open.
$PROCESS = @('slipcase-desktop', 'slipcase-open')

# Where the shots land. Not committed: dist is where every built artefact goes.
if (-not $OutDir) { $OutDir = Join-Path $root 'dist\store' }

# --- the desktop's theme, and the stream that says a file was downloaded -----

$PERSONALIZE = 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize'

function Set-Theme([string] $which) {
    $light = if ($which -eq 'light') { 1 } else { 0 }
    New-Item -Path $PERSONALIZE -Force | Out-Null
    Set-ItemProperty -Path $PERSONALIZE -Name AppsUseLightTheme -Value $light -Type DWord
    # Read back. The application reads this at startup and a value that did not
    # take gives a frame identical to its pair, which is a duplicate nobody
    # notices until the listing is up.
    $got = (Get-ItemProperty -Path $PERSONALIZE -Name AppsUseLightTheme).AppsUseLightTheme
    if ($got -ne $light) {
        Write-Error "shots.ps1: asked for the $which theme and the registry reads $got"
    }
    Write-Host "  desktop set to $which"
}

function New-ArrivedContainer {
    Copy-Item -LiteralPath $CONTAINER -Destination $ARRIVED -Force
    # What a browser writes on a downloaded file. ZoneId 3 is the internet
    # zone, which is what the provenance line is about.
    Set-Content -LiteralPath $ARRIVED -Stream Zone.Identifier -Value "[ZoneTransfer]`r`nZoneId=3"
    $stream = Get-Item -LiteralPath $ARRIVED -Stream Zone.Identifier -ErrorAction SilentlyContinue
    if (-not $stream) {
        Write-Error "shots.ps1: the Zone.Identifier did not stick to $ARRIVED - is dist on a filesystem that carries streams?"
    }
    Write-Host '  the second container is marked as downloaded'
}

# --- the shots --------------------------------------------------------------

# How each container is opened. With an AUMID the packaged build answers, which
# is what a person installs; without one the shell's association does.
function Opens([string] $path) {
    if ($Aumid) { return @('package', $Aumid, $path) }
    return @('shell', $path)
}

function Get-Shots {
    # Light first, because the product page shows the first picture largest and
    # a fresh Windows runs apps light.
    Shot '01-light' -Launch (Opens $CONTAINER) -Before { Set-Theme 'light' }

    Shot '02-light-arrived-from-elsewhere' -Launch (Opens $ARRIVED) `
        -Before { Set-Theme 'light'; New-ArrivedContainer }

    # The same two again, in dark. The only difference between 01 and 03 is the
    # desktop's theme: a shopper comparing them sees the application, not two
    # different demonstrations.
    Shot '03-dark' -Launch (Opens $CONTAINER) -Before { Set-Theme 'dark' }

    Shot '04-dark-arrived-from-elsewhere' -Launch (Opens $ARRIVED) `
        -Before { Set-Theme 'dark'; New-ArrivedContainer }
}

if (-not (Test-Path -LiteralPath $CONTAINER)) {
    Write-Error "shots.ps1: no container at $CONTAINER - run packaging/demo-container.sh first"
}

Take-Shots -Launch (Opens $CONTAINER) -Process $PROCESS `
    -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Reference:$Reference
