# Take a set of store screenshots, given the recipes for them.
# Generated by ship; edit internal/generate/templates and run ship sync.
#
# `shots.ps1` beside this is the half that is a product's - which document,
# which frames, and what has to happen in the window before each shutter. It
# dot-sources this file, declares its shots with `Shot`, and hands the set to
# `Take-Shots`. Everything here is the same in every repository, which is why
# it is not in there:
#
#     . "$PSScriptRoot\take-shots.ps1"
#
#     function Get-Shots {
#         Shot '01-window' @()
#         Shot '02-a-correction' @("double $A_CELL", 'key ctrl+a', "type 4.2")
#         Shot '03-another-document' -Launch @('shell', $OTHER)
#     }
#
#     Take-Shots -Launch @('shell', $DOCUMENT) -Process 'thing-desktop' `
#         -Width $WIDTH -Height $HEIGHT -OutDir $OutDir -Reference:$Reference
#
# `Get-Shots` describes the set rather than taking it, so the whole set is read
# before any of it runs. `screenshot.ps1` is the driver under all of it and
# knows nothing about any product; its header has the four actions a recipe may
# use and what `-Launch` accepts.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

function Refuse([string] $message) { Write-Error "shots.ps1: $message" }

# A shot is a name, what to do to the window, and - where this shot is not like
# the rest of the set - what to launch for it. A set whose frames open different
# documents is ordinary: slipcase-desktop photographs one container and then a
# second carrying a `Zone.Identifier`, and odox photographs three applications.
function Shot {
    param(
        [Parameter(Mandatory = $true, Position = 0)][string] $Name,
        [Parameter(Position = 1)][string[]] $Actions = @(),
        # Overrides for this shot alone. Unset means the set's.
        [string[]] $Launch,
        [string[]] $Process,
        [int] $Settle = 0,
        # Run before the application is launched for this shot. What belongs
        # here is state the application reads at startup and no click can
        # reach: the desktop's theme, a preference file, an alternate data
        # stream on the document.
        [scriptblock] $Before
    )
    [pscustomobject]@{
        Name = $Name; Actions = $Actions
        Launch = $Launch; Process = $Process; Settle = $Settle; Before = $Before
    }
}

function Take-Shots {
    param(
        # How the application starts, and whose window to photograph.
        # `screenshot.ps1`'s header has the three launch verbs.
        [Parameter(Mandatory = $true)][string[]] $Launch,
        [Parameter(Mandatory = $true)][string[]] $Process,
        [Parameter(Mandatory = $true)][int] $Width,
        [Parameter(Mandatory = $true)][int] $Height,
        [Parameter(Mandatory = $true)][string] $OutDir,
        # One plain capture and nothing else, which is what a coordinate gets
        # measured off.
        [switch] $Reference,
        # Seconds to wait after the window is sized before capturing. A large
        # document wants more than the driver's default.
        [int] $Settle = 0
    )

    $driver = Join-Path $PSScriptRoot 'screenshot.ps1'
    if (-not (Test-Path $driver)) { Refuse "no screenshot.ps1 beside $PSScriptRoot" }
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

    # Splatted into `& $driver`, which is a PowerShell call and binds each key
    # to the parameter of that name. Splatting a *native* command is a different
    # thing entirely - there the hashtable is stringified and the receiving
    # program sees one argument - so this shape is only safe because the driver
    # is a script.
    function Arguments($shot) {
        $a = @{
            Launch = $Launch; Process = $Process
            Width  = $Width; Height = $Height
        }
        if ($Settle -gt 0) { $a['Settle'] = $Settle }
        if ($null -ne $shot) {
            if ($shot.Launch) { $a['Launch'] = $shot.Launch }
            if ($shot.Process) { $a['Process'] = $shot.Process }
            if ($shot.Settle -gt 0) { $a['Settle'] = $shot.Settle }
        }
        return $a
    }

    # The reference frame is what an unmeasured constant is measured off, so it
    # has to be reachable while that constant is still empty - before the check
    # below and not after it.
    if ($Reference) {
        $out = Join-Path $OutDir 'reference.png'
        Write-Host 'shots.ps1: reference'
        $common = Arguments $null
        & $driver @common -Out $out
        Write-Host "shots.ps1: read the coordinates off $out and fill them in at the top of shots.ps1"
        return
    }

    $shots = @(Get-Shots)
    if ($shots.Count -eq 0) { Refuse 'Get-Shots declared no shots' }

    # A recipe naming a control that has never been measured would send its
    # click to the frame's corner, and a click that lands on nothing is a frame
    # that shows none of what it was for - which is the failure a driven
    # screenshot exists to correct. So an unmeasured control stops the set
    # rather than spoiling one of it.
    $unmeasured = @($shots |
        Where-Object { $_.Actions -match '^(click|double) *$' } |
        ForEach-Object { $_.Name })
    if ($unmeasured.Count -gt 0) {
        Refuse ("these shots name a control that has never been measured at " +
            "${Width}x${Height}: " + ($unmeasured -join ', ') + ". Take a " +
            "reference frame with -Reference, read the coordinates off it, and " +
            "fill in the empty constants at the top of shots.ps1.")
    }

    # The driver refuses by writing a terminating error, which comes back
    # through the call rather than as an exit code: `&` on a script runs it in
    # this process, and $LASTEXITCODE is the last *native* command's.
    $taken = 0
    foreach ($shot in $shots) {
        $out = Join-Path $OutDir "$($shot.Name).png"
        Write-Host "shots.ps1: $($shot.Name)"
        if ($shot.Before) { & $shot.Before }
        $common = Arguments $shot
        & $driver @common -Out $out -Do $shot.Actions
        $taken++
    }

    # A set that came back short is a set somebody submits without noticing, so
    # the count is said rather than left to be counted.
    Write-Host "shots.ps1: $taken shot(s) in $OutDir"
}
