#!/bin/sh
# The Mac App Store screenshots, as recipes rather than as prose.
#
# `screenshot.sh` beside this is the driver and knows nothing about Slipcase,
# and `take-shots.sh` beside that is the harness; both are generated by ship
# and the same in every repository with a window to photograph. This file is
# the part that is Slipcase's — which container, which frames, and what the
# desktop has to look like before the shutter.
#
#     ./packaging/demo-container.sh
#     ./packaging/demo-container.sh --lang de
#     ./packaging/macos/shots.sh --app dist/Slipcase.app
#     ./packaging/macos/shots.sh --app dist/Slipcase.app --lang de
#
# WHAT THE SET SHOWS, AND WHY
#
# An edit is under way in three of the four. Apple rejected Segler's first set
# under guideline 2.3.3 - *the screenshots do not show the actual app in use* -
# for four frames of a window at rest, and the Microsoft set here is exactly
# that shape: two containers photographed twice with nothing happening. It
# passes there and would not pass here.
#
# The fourth is the one thing a still frame can show without an edit: the same
# container carrying a quarantine attribute, so the card's provenance line
# reads that it arrived from elsewhere and the content file will carry that.
#
# THE ACTIONS STAY INSIDE THE DOCUMENT
#
# Coordinates are read off a frame at the size declared here, and the tree is
# the only part of the window that holds still between languages, because it is
# laid out by the document and the document is the same shape in both. The
# toolbar is not: `Speichern` sits 33 pixels right of `Save`, and the card's
# `Entpacken ...` 21 right of `Extract...`, so a recipe that pressed a toolbar
# button would photograph one thing in English and another in German.
#
# Nothing typed here is outside ASCII. Whether the driver's `--type` carries a
# German umlaut through CGEventPost has not been measured, and a screenshot is
# not where to find out.
#
# LIGHT LEADS, AND THREE OF FOUR ARE LIGHT
#
# The application follows the system appearance, a fresh macOS installation is
# light, and the product page shows the first picture largest. Dark is worth a
# slot because following the appearance is worth showing, and worth only one.
#
# THE APPEARANCE IS THE DESKTOP'S
#
# No control in the window changes it, so it is set before each launch. The
# driver stops whatever is running and launches again for every frame, so a
# value written here is read at the start it belongs to. It is read back,
# because a frame taken after an appearance that did not take is a duplicate of
# its pair, and that is the sort of thing that reaches a listing.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "${here}/../.." && pwd)

# --- the configuration ------------------------------------------------------

# App Store Connect takes 1440x900 for macOS, and every coordinate below was
# read off a frame of that size. Change it and they all move.
WIDTH=1440
HEIGHT=900

OUTDIR="${root}/dist/screenshots"

# What `packaging/demo-container.sh` builds, per language. Its archive
# timestamps are pinned, so any machine rebuilds the same bytes and the
# pictures match the container the review notes send a tester to.
english_container="${root}/dist/quarterly-report.pdf.slpc"
german_container="${root}/dist/quartalsbericht.pdf.slpc"

# --- the appearance, and the container that arrived from elsewhere -----------

# Asked of System Events rather than written with `defaults`.
#
# **`defaults write -g AppleInterfaceStyle Dark` is not enough, and it reads
# back as though it were.** It writes the value and `defaults read` returns it,
# because both go through the same preferences cache; the window server is
# never told, and an application launched afterwards still draws light.
# Measured 2026-09-17: the dark frame came back a pixel-for-pixel duplicate of
# its light pair, which is the failure the read-back was there to prevent.
#
# System Events sets it the way the Settings pane does. It is already trusted
# for Accessibility on a runner, which is what the driver needs anyway.
appearance() {
    case "$1" in
        light) want=false ;;
        dark) want=true ;;
        *) echo "shots.sh: appearance is light or dark, not $1" >&2; exit 2 ;;
    esac
    osascript -e "tell application \"System Events\" to tell appearance preferences to set dark mode to ${want}" >/dev/null
    sleep 1
    got=$(osascript -e 'tell application "System Events" to tell appearance preferences to get dark mode')
    [ "$got" = "$want" ] || {
        echo "shots.sh: asked for $1 and the desktop reads dark mode ${got}" >&2
        exit 1
    }
    echo "shots.sh: desktop set to $1"
}

# A copy in the Downloads folder, marked the way a download is. The path is in
# the frame, above the card, so the picture says where the container came from
# before the card's provenance line does - and a copy rather than a mark on the
# original, so a rerun does not find the first frame's container already
# carrying the attribute the second frame is about.
arrived() {
    mkdir -p "$(dirname -- "$2")"
    cp "$1" "$2"
    xattr -w com.apple.quarantine '0083;68ae0000;Safari;' "$2"
    xattr -p com.apple.quarantine "$2" >/dev/null ||
        { echo "shots.sh: the quarantine attribute did not stick to $2" >&2; exit 1; }
    echo "shots.sh: the second container is marked as downloaded"
}

# --- which container each language opens ------------------------------------

# Both containers are staged somewhere that reads like a person's machine. The
# path is in the frame, in the window, so what is photographed is what the
# listing advertises: opening the checkout's copy would put a build directory
# there, and a runner would put its own workspace there.
for_language() {
    case "$1" in
        en|en-US|en-us) built=$english_container ;;
        de|de-DE|de-de) built=$german_container ;;
        *) echo "shots.sh: no set is written for $1" >&2; exit 2 ;;
    esac
    [ -f "$built" ] || {
        echo "shots.sh: no container at ${built}" >&2
        echo "  ./packaging/demo-container.sh --lang $1" >&2
        exit 1
    }
    staged="${HOME}/Documents"
    mkdir -p "$staged"
    plain="${staged}/$(basename "$built")"
    cp "$built" "$plain"
    marked="${HOME}/Downloads/$(basename "$built")"
    arrived "$plain" "$marked"
    document=$plain
}

# --- the shots --------------------------------------------------------------

# Where the tree's controls are at 1440x900. Read off `00-reference.png`, which
# `--reference` takes; change WIDTH or HEIGHT and both move.
#
# The title's value field, which is the first editable row under the two
# comment lines.
TITLE_VALUE=366,306
# The kind beside `pages`, which offers the conversions an integer allows.
PAGES_KIND=270,394

# What gets typed into the title. Different from what is in the document, so
# the edit is visible, and short enough to read at a glance in a listing.
english_typed="Quarterly Report - Northwind, revision 2"
german_typed="Quartalsbericht - Nordwind, Fassung 2"

shots() {
    case "$lang" in
        de|de-DE|de-de) typed=$german_typed ;;
        *) typed=$english_typed ;;
    esac

    # The title being rewritten: the field focused and holding new text, and
    # Save, Undo and Redo coming on in the toolbar. This is the frame the
    # Microsoft set most lacks - the application in use.
    appearance light
    document=$plain
    shot 01-light-editing-a-value \
        --click "$TITLE_VALUE" --key cmd+a --type "$typed"

    # The container that arrived from elsewhere. The card's provenance line is
    # the one thing here worth a slot that a still frame can show, and the
    # content file the reader extracts carries the marking onward.
    document=$marked
    shot 02-light-arrived-from-elsewhere

    # The kind menu open on an integer, which is what "every value has a kind
    # menu offering the conversions it allows" looks like.
    document=$plain
    shot 03-light-the-kind-menu \
        --click "$PAGES_KIND"

    # The same edit in the dark appearance. The only difference from 01 is the
    # desktop's, so a reader comparing them sees the application rather than two
    # different demonstrations.
    appearance dark
    shot 04-dark-editing-a-value \
        --click "$TITLE_VALUE" --key cmd+a --type "$typed"
}

. "${here}/take-shots.sh"
take_shots "$@"
