#!/bin/sh
# The Mac App Store screenshots, as recipes rather than as prose.
#
# `screenshot.sh` beside this is the driver and knows nothing about Slipcase,
# and `take-shots.sh` beside that is the harness; both are generated by ship
# and the same in every repository with a window to photograph. This file is
# the part that is Slipcase's — which container, which frames, and what the
# desktop has to look like before the shutter.
#
#     ./packaging/demo-container.sh
#     ./packaging/demo-container.sh --lang de
#     ./packaging/macos/shots.sh --app dist/Slipcase.app
#     ./packaging/macos/shots.sh --app dist/Slipcase.app --lang de
#
# WHAT THE SET SHOWS, AND WHY
#
# The same two containers as the Microsoft set, in the same two appearances.
# The second container is the first one carrying a quarantine attribute, so the
# card's provenance line reads *This container arrived from elsewhere, and the
# payload will carry that* — which is the one thing in this application worth a
# slot that a still frame can show without an edit.
#
# Light leads, and that is a decision rather than a preference. The application
# follows the system appearance, a fresh macOS installation is light, and the
# product page shows the first picture largest.
#
# THE APPEARANCE IS THE DESKTOP'S
#
# No control in the window changes it, so it is set before each launch. The
# driver stops whatever is running and launches again for every frame, so a
# value written here is read at the start it belongs to. It is read back,
# because a frame taken after an appearance that did not take is a duplicate of
# its pair, and that is the sort of thing that reaches a listing.
#
# Author: David M. Anderson
# Built with AI assistance (Claude, Anthropic)

set -eu

here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
root=$(CDPATH= cd -- "${here}/../.." && pwd)

# --- the configuration ------------------------------------------------------

# App Store Connect takes 1440x900 for macOS, and every coordinate below was
# read off a frame of that size. Change it and they all move.
WIDTH=1440
HEIGHT=900

OUTDIR="${root}/dist/screenshots"

# What `packaging/demo-container.sh` builds, per language. Its archive
# timestamps are pinned, so any machine rebuilds the same bytes and the
# pictures match the container the review notes send a tester to.
english_container="${root}/dist/quarterly-report.pdf.slpc"
german_container="${root}/dist/quartalsbericht.pdf.slpc"

# --- the appearance, and the container that arrived from elsewhere -----------

appearance() {
    case "$1" in
        light) defaults delete -g AppleInterfaceStyle 2>/dev/null || true ;;
        dark) defaults write -g AppleInterfaceStyle -string Dark ;;
    esac
    got=$(defaults read -g AppleInterfaceStyle 2>/dev/null || echo light)
    case "$1:$got" in
        light:light|dark:Dark) echo "shots.sh: desktop set to $1" ;;
        *) echo "shots.sh: asked for $1 and the desktop reads ${got}" >&2; exit 1 ;;
    esac
}

# A copy under a second name, marked the way a download is, so that a rerun
# does not find the first frame's container already carrying the attribute the
# second frame is about.
arrived() {
    cp "$1" "$2"
    xattr -w com.apple.quarantine '0083;68ae0000;Safari;' "$2"
    xattr -p com.apple.quarantine "$2" >/dev/null ||
        { echo "shots.sh: the quarantine attribute did not stick to $2" >&2; exit 1; }
    echo "shots.sh: the second container is marked as downloaded"
}

# --- which container each language opens ------------------------------------

# Both containers are staged somewhere that reads like a person's machine. The
# path is in the frame, in the window, so what is photographed is what the
# listing advertises: opening the checkout's copy would put a build directory
# there, and a runner would put its own workspace there.
for_language() {
    case "$1" in
        en|en-US|en-us) built=$english_container ;;
        de|de-DE|de-de) built=$german_container ;;
        *) echo "shots.sh: no set is written for $1" >&2; exit 2 ;;
    esac
    [ -f "$built" ] || {
        echo "shots.sh: no container at ${built}" >&2
        echo "  ./packaging/demo-container.sh --lang $1" >&2
        exit 1
    }
    staged="${HOME}/Documents"
    mkdir -p "$staged"
    plain="${staged}/$(basename "$built")"
    cp "$built" "$plain"
    marked="${plain%.slpc}-arrived.slpc"
    arrived "$plain" "$marked"
    document=$plain
}

# --- the shots --------------------------------------------------------------

shots() {
    appearance light
    document=$plain
    shot 01-light

    document=$marked
    shot 02-light-arrived-from-elsewhere

    appearance dark
    document=$plain
    shot 03-dark

    document=$marked
    shot 04-dark-arrived-from-elsewhere
}

. "${here}/take-shots.sh"
take_shots "$@"
